2:2 error:continue cannot be used outside of a loop